### ISSUE TITLE
【Enhancement-Upgrade】建议支持热更新，用户去重复下载新应用的动力不足

### ISSUE THREAD

**Issue by Sandu1213** [biyidev/biyi#12]
**Reproduce：**
 - OS Version: Win10  专业版  (19042.1237)

![image](https://user-images.githubusercontent.com/21214285/136921540-62a93811-c9de-43d3-9b8e-d33b7c320adf.png)

**Comment by lijy91** [comment]
后续在 https://github.com/biyidev/biyi/issues/52 进行跟进
