### ISSUE TITLE
Windows下打开窗口空白

### ISSUE THREAD

**Issue by levie-vans** [biyidev/biyi#25]
![image](https://user-images.githubusercontent.com/66657337/139609776-10c20e0d-21f1-4828-92ca-4899c46a5506.png)
打开比译，窗口一片空白。
系统版本：Windows10 19043
比译版本：0.32
![image](https://user-images.githubusercontent.com/66657337/139609865-099c61b9-fa21-4745-86f5-39e79f59bcc5.png)

**Comment by lijy91** [comment]
已修复，将在下一版本发布

**Comment by o000u** [comment]
刚测了0.36版，依然会空白。
系统：Windows 11 专业版 Insider Preview 22533.1001

**Comment by o000u** [comment]
![image](https://user-images.githubusercontent.com/33189913/154798537-3db8aeaf-8463-4faf-a257-42b1a386566b.png)
