### ISSUE TITLE
德语 发音

### ISSUE THREAD

**Issue by eraserofmemory** [biyidev/biyi#46]
希望添加德语发音
最好其它语种也能加上发音功能

其实我更想使用个人词典
具体来说，使用者
A 输入
1输入某串文字
2录入对应语音
B 查询
1查询某串文字
2听到对应语音

翻译对我来说没有语音重要
所以只要有文字和语音就行
也许因为很多人对功能的幻想过于执着
这种需求便会显得过于简朴

best wishes

**Comment by lijy91** [comment]
目前发音取决于翻译引擎是否提供，如果有专有的德语引擎，可告知一下，后续可添加。
