### ISSUE TITLE
flutter run for Linux get error

### ISSUE THREAD

**Issue by zzugyl** [biyidev/biyi#56]
clone code based on commit "6c70822d45f386649250e09404fa97b6dd42f8a3"
when come  to `flutter run -d linux` , get error
`A RenderFlex overflowed by 25 pixels on the bottom.`
![Screenshot at 2022-01-18 21-39-52](https://user-images.githubusercontent.com/27466768/149948969-246dff46-e676-4c06-9be4-59e5db45aa4e.png)

**Comment by lijy91** [comment]
Fixed, will be released in next version
