### ISSUE TITLE
package for aur

### ISSUE THREAD

**Issue by CRAG666** [biyidev/biyi#57]
I think that one way to bring this project to more people is to publish it in a repository, in this case aur (archlinux user repository) is a very good option. I would like to be able to install this project from aur.

**Comment by lijy91** [comment]
Thank you for your suggestion. At present, the main focus is still on improving the function, and flutter must have pub installed at the beginning, so it is not a big problem.

**Comment by lijy91** [comment]
Currently the focus will be on windows + macOS platforms, no plans to release to aur.
