### ISSUE TITLE
0.3.6Windows下打开窗口依然是空白

### ISSUE THREAD

**Issue by o000u** [biyidev/biyi#60]
比译版本：0.3.6
![image](https://user-images.githubusercontent.com/33189913/154798678-be2ec428-61ac-46c6-beb7-3f0cc4873cef.png)
![image](https://user-images.githubusercontent.com/33189913/154798707-afdd6302-b319-4a79-99c2-0d65dae762e8.png)

**Comment by keenwon** [comment]
+1 开机的时候会直接展示空白，后面使用时正常的

**Comment by lijy91** [comment]
请安装 0.4.0 看能不能正常

https://apps.microsoft.com/store/detail/%E6%AF%94%E8%AF%91/9P3H9NZKW0V6?hl=zh-cn&gl=CN
