### ISSUE TITLE
Could not find package uni_translate at "..\uni_translate\packages\uni_translate"

### ISSUE THREAD

**Issue by HaloWang** [biyidev/biyi#64]
是不是路径配置有误? 我用 pub.dev 上的 uni_translate 可以吗?

**Comment by HaloWang** [comment]
可能, 你们项目本地的 OCR 库 apikey 是私有的?

**Comment by lijy91** [comment]
由于目前在本地进行部分重构，所以导致一些依赖冲突，可以关注后续的代码的更新。

**Comment by Muzzie3** [comment]
![image](https://user-images.githubusercontent.com/37406676/169704431-1a324d1b-099a-41a9-a3ca-3ffae82fc808.png)
I have the same issue, will you fix it?
