### ISSUE TITLE
能否提供deb安装包

### ISSUE THREAD

**Issue by lzxiaohuihui** [biyidev/biyi#67]
之前使用体验非常不错，但是旧版本的deb已废弃

**Comment by lijy91** [comment]
已上传到 Releases，但可以需要装 [GStreamer](https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c) 才能正常使用
```
sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
```

**Comment by lzxiaohuihui** [comment]
非常感谢！可以正常使用了。
