### ISSUE TITLE
有道翻译 API 的结果显示 ErrorCode: 0

### ISSUE THREAD

**Issue by AptX395** [biyidev/biyi#69]
比译更新到 0.4.0 后对有道翻译 API 的翻译结果处理有误。

根据有道翻译 API 的官方文档，`ErrorCode: 0` 对应的状态为`正常`。

麻烦开发者及时修复~非常感谢！

祝比译越来越好😊

**Comment by lijy91** [comment]
已修复，将在下一版本中发布
