### ISSUE TITLE
软件的 Windows 安装程序将安装信息写至 32 位注册表项

### ISSUE THREAD

**Issue by SpecterShell** [biyidev/biyi#71]
虽然软件本体是 64 位的，但是安装程序将安装信息写到了
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{E8B1CB29-5C24-D882-3CEF-F8A7263BC63D}`（32位项）
而不是
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{E8B1CB29-5C24-D882-3CEF-F8A7263BC63D}`（64 位

导致软件会被一些软件卸载工具直接标记为 32 位程序。
![image](https://user-images.githubusercontent.com/56779163/172983906-14381993-3582-48e6-be19-cc688715d814.png)

**Comment by lijy91** [comment]
感谢反馈，将更新打包工具 https://github.com/leanflutter/flutter_distributor/issues/81

**Comment by lijy91** [comment]
请问上面截图这个是什么工具？

**Comment by SpecterShell** [comment]
Geek Uninstaller

**Comment by lijy91** [comment]
请更新到0.5.0
