### ISSUE TITLE
windows下输入框仅可以显示一行文本？

### ISSUE THREAD

**Issue by yayiji** [biyidev/biyi#72]
不知道是不是我遗漏了什么设置，输入框仅仅可以显示一行，导致我无法在翻译页面对照原文和译文。并且，如果我们手动输入文本进行翻译，也不知道如何进行换行

![image](https://user-images.githubusercontent.com/12449762/173191750-7fd41dbb-82db-4bd7-8e92-7cb27ad44a71.png)

**Comment by lijy91** [comment]
输入设置中修改为 用 Command + Enter 提交 即可输入多行。
<img width="392" alt="image" src="https://user-images.githubusercontent.com/3889523/173210118-e117dbdf-37ff-4479-8fda-4a5c7bd79e47.png">
