### ISSUE TITLE
Ubuntu 20.04 不显示托盘图标

### ISSUE THREAD

**Issue by seahurt** [biyidev/biyi#74]
一开始我以为这个软件直接退出了，后来才发现在托盘有一个位置，可以点击弹出菜单，但就是没有图标。或者说图标是黑色的，与托盘融为一体了。

![image](https://user-images.githubusercontent.com/3347603/174531445-e81b3d60-f635-43fa-9855-4c139a9ee9d6.png)

**Comment by lijy91** [comment]
收到，后续将优化

**Comment by lijy91** [comment]
请更新到 0.5.0
