### ISSUE TITLE
0.4.0 tag points to a empty branch

### ISSUE THREAD

**Issue by linsui** [biyidev/biyi#76]
Could you please tag on the real commit? Thanks!

**Comment by lijy91** [comment]
Versions after 0.4.0 will no longer be open source

**Comment by linsui** [comment]
Then could you please fix the license?

**Comment by lijy91** [comment]
What license?

**Comment by linsui** [comment]
The readme says that the license is AGPL but it's not open source any more, right? Could you please declare that in the readme?

**Comment by lijy91** [comment]
The main branch also has source code for historical versions

**Comment by linsui** [comment]
@lijy91 It seems biyi is open source again?
