### ISSUE TITLE
”无法打开，因为apple无法检测其是否包含恶意软件，此软件需要更新“

### ISSUE THREAD

**Issue by Gaoxiao-ting** [biyidev/biyi#77]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/70355533/177091088-b1603673-503a-42c5-a861-3fd543d2dd65.png">
请问这种情况怎么解决呢

**Comment by lijy91** [comment]
请在设置->安全性与隐私 里允许打开比译
<img width="668" alt="image" src="https://user-images.githubusercontent.com/3889523/177093957-a4c26487-98a1-4173-9974-c22e634d062d.png">

**Comment by Gaoxiao-ting** [comment]
> 请在设置-> 安全性与隐私中允许打开比译 <img alt="图片" width="668" src="https://user-images.githubusercontent.com/3889523/177093957-a4c26487-98a1-4173-9974-c22e634d062d.png">
我的设置没有“任何来源”的选项呢
<img width="668" alt="image" src="https://user-images.githubusercontent.com/70355533/177235093-bfd778b3-c86b-4264-bd8b-7ba34a1f8a26.png">
