### ISSUE TITLE
m1 mac全屏模式下快捷键划词翻译时会自动切换到主屏幕

### ISSUE THREAD

**Issue by a610970751** [biyidev/biyi#81]
m1 mac全屏模式下快捷键划词翻译时会自动切换到主屏幕，建议在当前屏幕下中展示翻译结果

**Comment by d1y** [comment]
同样的问题
https://user-images.githubusercontent.com/45585937/189424107-2484698b-f463-49e8-965e-9a07e2b643e6.mov

**Comment by lijy91** [comment]
已修复，请更新到0.5.0
