### ISSUE TITLE
求支持deepL接口域名翻译

### ISSUE THREAD

**Issue by VectorZhao** [biyidev/biyi#86]
类似这个插件实现的功能[https://github.com/clubxdev/bob-plugin-deeplx](https://github.com/clubxdev/bob-plugin-deeplx)
deepl的api太难申请，目前利用接口域名是个不错的选择，希望加入这个功能！

**Comment by lijy91** [comment]
由于 zu1k/deepl 镜像已经被移除，所以该功能无法实现了

**Comment by VectorZhao** [comment]
> 由于 zu1k/deepl 镜像已经被移除，所以该功能无法实现了

https://hub.docker.com/r/kanikig/deepl-bk

这里有备份
