### ISSUE TITLE
Mac M1 无法启动(v0.4.0)

### ISSUE THREAD

**Issue by millken** [biyidev/biyi#89]
"AudioContext configuration is not available on macOS"
flutter: /Users/millken/Library/Containers/com.biyidev.app/Data/Documents/local
2
device_info_plus_macos/CwlSysctl.swift:163: Fatal error: 'try!' expression unexpectedly raised an error: device_info_plus_macos.Sysctl.Error.posixError(Darwin.POSIXErrorCode)
[1]    30856 trace trap  /Applications/biyi.app/Contents/MacOS/biyi

**Comment by GZGavinZhao** [comment]
https://github.com/fluttercommunity/plus_plugins/pull/826, 需要更新版本。

**Comment by lijy91** [comment]
请更新到0.5.0
